# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e38abe481abbc964d37d8727902fe1e0debc39d49bf4e4f621d832302d0492f5f6c82f9ff3083ec91b1ae31d7b162027fa8f70bc1af10b5d906b7c1d9bcb2460

test:
  secret_key_base: 2d191179d2c11ac9eb901035afd1061da26865df7c1801eb5d245882996df34d1fd82eb3b2fc25fa4955f3ef29a4dd6cae7f5028b75528415d261e81a6bbb20c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
